#include <signature.h>
#include <tools.h>
#include <quaternion_data.h>
#include <id2iso.h>
#include <torsion_constants.h>
#include <encoded_sizes.h>

#include <stdio.h>
#include "intbig.h"
#include <bench.h> 

int ibz_probab_prime(const ibz_t *n, int reps);
void ibz_print(const ibz_t *num, int base);
int ibz_set_from_str(ibz_t *num, const char *str, int base);
void test_norm_with_factors(size_t runs, const quat_represent_integer_params_t *params);

// compute the commitment with ideal to isogeny clapotis
// and apply it to the basis of E0 (together with the multiplication by some scalar u)
static bool
commit(ec_curve_t *E_com, ec_basis_t *basis_even_com, quat_left_ideal_t *lideal_com)
{

    bool found = false;
    // Origin algrithm
    found = quat_sampling_random_ideal_O0_given_norm(lideal_com, &COM_DEGREE, 1, &QUAT_represent_integer_params, NULL);
    // Algorithm 2 3mod4
    // found = quat_constant_random_O0_ideal_norm_3mod4(lideal_com, &QUAT_represent_integer_params, &SEC_DEGREE, &U0, &V0, &X0, &Y0);
    // Algorithm 3 universal 3mod4
    // found = quat_constant_random_O0_ideal_norm_universal(lideal_com, &QUAT_represent_integer_params, &SEC_DEGREE, &X0, &Y0, &MINUS_Y0, &X0_PLUS_Y0);

    // replacing it with a shorter prime norm equivalent ideal
    found = found && quat_lideal_prime_norm_reduced_equivalent(
                         lideal_com, &QUATALG_PINFTY, QUAT_primality_num_iter, QUAT_equiv_bound_coeff);
    // ideal to isogeny clapotis
    found = found && dim2id2iso_arbitrary_isogeny_evaluation(basis_even_com, E_com, lideal_com);
    return found;
}

static void
compute_challenge_ideal_signature(quat_left_ideal_t *lideal_chall_two, const signature_t *sig, const secret_key_t *sk)
{
    ibz_vec_2_t vec;
    ibz_vec_2_init(&vec);

    // vec is a vector [1, chall_coeff] coefficients encoding the kernel of the challenge
    // isogeny as B[0] + chall_coeff*B[1] where B is the canonical basis of the
    // 2^TORSION_EVEN_POWER torsion of EA
    ibz_set(&vec[0], 1);
    ibz_copy_digit_array(&vec[1], sig->chall_coeff);

    // now we compute the ideal associated to the challenge
    // for that, we need to find vec such that
    // the kernel of the challenge isogeny is generated by vec[0]*B0[0] + vec[1]*B0[1] where B0
    // is the image through the secret key isogeny of the canonical basis E0
    ibz_mat_2x2_eval(&vec, &(sk->mat_BAcan_to_BA0_two), &vec);

    // lideal_chall_two is the pullback of the ideal challenge through the secret key ideal
    id2iso_kernel_dlogs_to_ideal_even(lideal_chall_two, &vec, TORSION_EVEN_POWER);
    assert(ibz_cmp(&lideal_chall_two->norm, &TORSION_PLUS_2POWER) == 0);

    ibz_vec_2_finalize(&vec);
}

static void
sample_response(quat_alg_elem_t *x, const quat_lattice_t *lattice, const ibz_t *lattice_content)
{
    ibz_t bound;
    ibz_init(&bound);
    ibz_pow(&bound, &ibz_const_two, SQIsign_response_length);
    ibz_sub(&bound, &bound, &ibz_const_one);
    ibz_mul(&bound, &bound, lattice_content);

    int ok UNUSED = quat_lattice_sample_from_ball(x, lattice, &QUATALG_PINFTY, &bound);
    assert(ok);

    ibz_finalize(&bound);
}

static void
compute_response_quat_element(quat_alg_elem_t *resp_quat,
                              ibz_t *lattice_content,
                              const secret_key_t *sk,
                              const quat_left_ideal_t *lideal_chall_two,
                              const quat_left_ideal_t *lideal_commit)
{
    quat_left_ideal_t lideal_chall_secret;
    quat_lattice_t lattice_hom_chall_to_com, lat_commit;

    // Init
    quat_left_ideal_init(&lideal_chall_secret);
    quat_lattice_init(&lat_commit);
    quat_lattice_init(&lattice_hom_chall_to_com);

    // lideal_chall_secret = lideal_secret * lideal_chall_two
    quat_lideal_inter(&lideal_chall_secret, lideal_chall_two, &(sk->secret_ideal), &QUATALG_PINFTY);

    // now we compute lideal_com_to_chall which is dual(Icom)* lideal_chall_secret
    quat_lattice_conjugate_without_hnf(&lat_commit, &(lideal_commit->lattice));
    quat_lattice_intersect(&lattice_hom_chall_to_com, &lideal_chall_secret.lattice, &lat_commit);

    // sampling the smallest response
    ibz_mul(lattice_content, &lideal_chall_secret.norm, &lideal_commit->norm);
    sample_response(resp_quat, &lattice_hom_chall_to_com, lattice_content);

    // Clean up
    quat_left_ideal_finalize(&lideal_chall_secret);
    quat_lattice_finalize(&lat_commit);
    quat_lattice_finalize(&lattice_hom_chall_to_com);
}

static void
compute_response_quat_element_extract(quat_alg_elem_t *resp_quat,
                                      ibz_t *lattice_content,
                                      quat_lattice_t *lattice_hom_chall_to_com,
                                      const secret_key_t *sk,
                                      const quat_left_ideal_t *lideal_chall_two,
                                      const quat_left_ideal_t *lideal_commit)
{
    quat_left_ideal_t lideal_chall_secret;
    quat_lattice_t lat_commit;

    // Init
    quat_left_ideal_init(&lideal_chall_secret);
    quat_lattice_init(&lat_commit);

    // lideal_chall_secret = lideal_secret * lideal_chall_two
    quat_lideal_inter(&lideal_chall_secret, lideal_chall_two, &(sk->secret_ideal), &QUATALG_PINFTY);

    // now we compute lideal_com_to_chall which is dual(Icom)* lideal_chall_secret
    quat_lattice_conjugate_without_hnf(&lat_commit, &(lideal_commit->lattice));
    quat_lattice_intersect(lattice_hom_chall_to_com, &lideal_chall_secret.lattice, &lat_commit);

    // sampling the smallest response
    ibz_mul(lattice_content, &lideal_chall_secret.norm, &lideal_commit->norm);
    // sample_response(resp_quat, lattice_hom_chall_to_com, lattice_content);

    // Clean up
    quat_left_ideal_finalize(&lideal_chall_secret);
    quat_lattice_finalize(&lat_commit);
    // quat_lattice_finalize(&lattice_hom_chall_to_com);
}

static void
compute_backtracking_signature(signature_t *sig, quat_alg_elem_t *resp_quat, ibz_t *lattice_content, ibz_t *remain)
{
    uint_fast8_t backtracking;
    ibz_t tmp;
    ibz_init(&tmp);

    ibz_vec_4_t dummy_coord;
    ibz_vec_4_init(&dummy_coord);

    quat_alg_make_primitive(&dummy_coord, &tmp, resp_quat, &MAXORD_O0);
    ibz_mul(&resp_quat->denom, &resp_quat->denom, &tmp);
    assert(quat_lattice_contains(NULL, &MAXORD_O0, resp_quat));

    // the backtracking is the common part of the response and the challenge
    // its degree is the scalar tmp computed above such that quat_resp is in tmp * O0.
    backtracking = ibz_two_adic(&tmp);
    sig->backtracking = backtracking;

    ibz_pow(&tmp, &ibz_const_two, backtracking);
    ibz_div(lattice_content, remain, lattice_content, &tmp);

    ibz_finalize(&tmp);
    ibz_vec_4_finalize(&dummy_coord);
}

static uint_fast8_t
compute_random_aux_norm_and_helpers(signature_t *sig,
                                    ibz_t *random_aux_norm,
                                    ibz_t *degree_resp_inv,
                                    ibz_t *remain,
                                    const ibz_t *lattice_content,
                                    quat_alg_elem_t *resp_quat,
                                    quat_left_ideal_t *lideal_com_resp,
                                    quat_left_ideal_t *lideal_commit)
{
    uint_fast8_t pow_dim2_deg_resp;
    uint_fast8_t exp_diadic_val_full_resp;

    ibz_t tmp, degree_full_resp, degree_odd_resp, norm_d;

    // Init
    ibz_init(&degree_full_resp);
    ibz_init(&degree_odd_resp);
    ibz_init(&norm_d);
    ibz_init(&tmp);

    quat_alg_norm(&degree_full_resp, &norm_d, resp_quat, &QUATALG_PINFTY);

    // dividing by n(lideal_com) * n(lideal_secret_chall)
    assert(ibz_is_one(&norm_d));
    ibz_div(&degree_full_resp, remain, &degree_full_resp, lattice_content);
    assert(ibz_cmp(remain, &ibz_const_zero) == 0);

    // computing the diadic valuation
    exp_diadic_val_full_resp = ibz_two_adic(&degree_full_resp);
    sig->two_resp_length = exp_diadic_val_full_resp;

    // removing the power of two part
    ibz_pow(&tmp, &ibz_const_two, exp_diadic_val_full_resp);
    ibz_div(&degree_odd_resp, remain, &degree_full_resp, &tmp);
    assert(ibz_cmp(remain, &ibz_const_zero) == 0);
#ifndef NDEBUG
    ibz_pow(&tmp, &ibz_const_two, SQIsign_response_length - sig->backtracking);
    assert(ibz_cmp(&tmp, &degree_odd_resp) > 0);
#endif

    // creating the ideal
    quat_alg_conj(resp_quat, resp_quat);

    // setting the norm
    ibz_mul(&tmp, &lideal_commit->norm, &degree_odd_resp);
    quat_lideal_create(lideal_com_resp, resp_quat, &tmp, &MAXORD_O0, &QUATALG_PINFTY);

    // now we compute the ideal_aux
    // computing the norm
    pow_dim2_deg_resp = SQIsign_response_length - exp_diadic_val_full_resp - sig->backtracking;
    ibz_pow(remain, &ibz_const_two, pow_dim2_deg_resp);
    ibz_sub(random_aux_norm, remain, &degree_odd_resp);

    // multiplying by 2^HD_extra_torsion to account for the fact that
    // we use extra torsion above the kernel
    for (int i = 0; i < HD_extra_torsion; i++)
        ibz_mul(remain, remain, &ibz_const_two);

    ibz_invmod(degree_resp_inv, &degree_odd_resp, remain);

    ibz_finalize(&degree_full_resp);
    ibz_finalize(&degree_odd_resp);
    ibz_finalize(&norm_d);
    ibz_finalize(&tmp);

    return pow_dim2_deg_resp;
}

// compute x0^2 + y0^2 = 1 mod N, and -y0, x0+y0 as inputs to Algorithm 3
static int
compute_auxiliary_parameters_for_alg3(const ibz_t *norm,
                                      ibz_t *x0,
                                      ibz_t *y0,
                                      ibz_t *minus_y0,
                                      ibz_t *x0_plus_y0)
{
    int ret = 1;
    ibz_t c, tmp, inv, rem, four;
    
    ibz_init(&c); ibz_init(&tmp); ibz_init(&inv); 
    ibz_init(&rem); ibz_init(&four);

    ibz_set(&four, 4);

    // compute c = -p^(-1) mod N
    if (!ibz_invmod(&c, &QUATALG_PINFTY.p, norm)) {
        ret = 0; 
        goto cleanup;
    }
    ibz_sub(&c, norm, &c); // c = -p^-1 mod N

    // compute based on the residue class of N mod 4.
    ibz_mod(&rem, norm, &four);
    if (ibz_cmp(&rem, &ibz_const_one) == 0) {
        // N = 1 mod 4
        ibz_t j;
        ibz_init(&j);

        // j = sqrt(-1) mod N
        ibz_sub(&tmp, norm, &ibz_const_one); 
        ibz_sqrt_mod_p(&j, &tmp, norm);

        // x0 = (c + 1) / 2 mod N
        ibz_add(x0, &c, &ibz_const_one);
        if (!ibz_is_even(x0)) {         
            ibz_add(x0, x0, norm); // add N to make x0 an even number. 
        }
        ibz_div(x0, &rem, x0, &ibz_const_two); 
        // x0 + N < 2N
        if (ibz_cmp(x0, norm) >= 0) {
            ibz_sub(x0, x0, norm);
        }

        // y0 = (c - 1) / 2 * (-j) mod N, -j = j^(-1)
        // tmp = (c - 1) / 2 mod N
        if (ibz_is_zero(&c)) {
            ibz_sub(&tmp, norm, &ibz_const_one); // 0 - 1 mod N = N - 1
        } 
        else {
            ibz_sub(&tmp, &c, &ibz_const_one);
        }
        if (!ibz_is_even(&tmp)) {       
            ibz_add(&tmp, &tmp, norm);  
        }
        ibz_div(&tmp, &rem, &tmp, &ibz_const_two);

        // (-j) = (N - j) mod N
        ibz_sub(&j, norm, &j);  
        ibz_mul(y0, &tmp, &j);
        ibz_mod(y0, y0, norm);       

        ibz_finalize(&j);
        
    } 
    else {
        // N = 3 mod 4
        ibz_t x_g, y_g, g, s;
        ibz_init(&x_g); ibz_init(&y_g); ibz_init(&g); ibz_init(&s);

        if (ibz_legendre(&c, norm) == 1) {
            // c is a quadratic residue
            ibz_sqrt_mod_p(x0, &c, norm);
            ibz_set(y0, 0);
        } 
        else {
            // c is not a quadratic residue 
            // find g = xg^2 + yg^2 which is a quadratic non-residual.
            while (1) {
                ibz_rand_interval(&x_g, &ibz_const_zero, norm);
                ibz_rand_interval(&y_g, &ibz_const_zero, norm);
                
                ibz_mul(&g, &x_g, &x_g);
                ibz_mul(&tmp, &y_g, &y_g);
                ibz_add(&g, &g, &tmp);
                ibz_mod(&g, &g, norm);

                if (!ibz_is_zero(&g) && ibz_legendre(&g, norm) == -1) {
                    break;
                }
            }

            // s = sqrt(c/g) mod N
            ibz_invmod(&inv, &g, norm);
            ibz_mul(&tmp, &c, &inv);
            ibz_mod(&tmp, &tmp, norm); 
            ibz_sqrt_mod_p(&s, &tmp, norm);

            // x0 = xg * s, y0 = yg * s
            ibz_mul(x0, &x_g, &s);
            ibz_mod(x0, x0, norm);
            ibz_mul(y0, &y_g, &s);
            ibz_mod(y0, y0, norm);
        }
        ibz_finalize(&x_g); ibz_finalize(&y_g); ibz_finalize(&g); ibz_finalize(&s);
    }

    // compute the auxiliary outputs: -y0 and x0+y0
    ibz_sub(minus_y0, norm, y0);
    ibz_mod(minus_y0, minus_y0, norm);

    ibz_add(x0_plus_y0, x0, y0);
    ibz_mod(x0_plus_y0, x0_plus_y0, norm);

cleanup:
    ibz_finalize(&c); ibz_finalize(&tmp); ibz_finalize(&inv); 
    ibz_finalize(&rem); ibz_finalize(&four);
    return ret;
}

static int
evaluate_random_aux_isogeny_signature(ec_curve_t *E_aux,
                                      ec_basis_t *B_aux,
                                      const ibz_t *norm,
                                      const quat_left_ideal_t *lideal_com_resp)
{
    int found = 0;
    ibz_t x0, y0, minus_y0, x0_plus_y0;
    ibz_init(&x0); ibz_init(&y0); 
    ibz_init(&minus_y0); ibz_init(&x0_plus_y0);

    quat_left_ideal_t lideal_aux;
    quat_left_ideal_t lideal_aux_resp_com;

    // Init
    quat_left_ideal_init(&lideal_aux);
    quat_left_ideal_init(&lideal_aux_resp_com);

    // sampling the ideal at random
    // size_t t = 1000;
    // algorithm 3 universal
    // BENCH_CODE_1(t);
    compute_auxiliary_parameters_for_alg3(norm, &x0, &y0, &minus_y0, &x0_plus_y0);
    found = quat_constant_random_O0_ideal_norm_universal(
          &lideal_aux, &QUAT_represent_integer_params, norm, &x0, &y0, &minus_y0, &x0_plus_y0
    );
    // BENCH_CODE_2("test");
    // origin algorithm
    // found = quat_sampling_random_ideal_O0_given_norm(
    //       &lideal_aux, norm, 0, &QUAT_represent_integer_params, &QUAT_prime_cofactor);

    if (found) {
        // pushing forward
        quat_lideal_inter(&lideal_aux_resp_com, lideal_com_resp, &lideal_aux, &QUATALG_PINFTY);

        // now we evaluate this isogeny on the basis of E0
        found = dim2id2iso_arbitrary_isogeny_evaluation(B_aux, E_aux, &lideal_aux_resp_com);

        // Clean up
        quat_left_ideal_finalize(&lideal_aux_resp_com);
        quat_left_ideal_finalize(&lideal_aux);

        ibz_finalize(&x0); ibz_finalize(&y0); 
        ibz_finalize(&minus_y0); ibz_finalize(&x0_plus_y0);
    }

    return found;
}

static int
compute_dim2_isogeny_challenge(theta_couple_curve_with_basis_t *codomain,
                               theta_couple_curve_with_basis_t *domain,
                               const ibz_t *degree_resp_inv,
                               int pow_dim2_deg_resp,
                               int exp_diadic_val_full_resp,
                               int reduced_order)
{
    // now, we compute the isogeny Phi : Ecom x Eaux -> Echl' x Eaux'
    // where Echl' is 2^exp_diadic_val_full_resp isogenous to Echal
    // ker Phi = <(Bcom_can.P,Baux.P),(Bcom_can.Q,Baux.Q)>

    // preparing the domain
    theta_couple_curve_t EcomXEaux;
    copy_curve(&EcomXEaux.E1, &domain->E1);
    copy_curve(&EcomXEaux.E2, &domain->E2);

    // preparing the kernel
    theta_kernel_couple_points_t dim_two_ker;
    copy_bases_to_kernel(&dim_two_ker, &domain->B1, &domain->B2);

    // dividing by the degree of the response
    digit_t scalar[NWORDS_ORDER];
    ibz_to_digit_array(scalar, degree_resp_inv);
    ec_mul(&dim_two_ker.T1.P2, scalar, reduced_order, &dim_two_ker.T1.P2, &EcomXEaux.E2);
    ec_mul(&dim_two_ker.T2.P2, scalar, reduced_order, &dim_two_ker.T2.P2, &EcomXEaux.E2);
    ec_mul(&dim_two_ker.T1m2.P2, scalar, reduced_order, &dim_two_ker.T1m2.P2, &EcomXEaux.E2);

    // and multiplying by 2^exp_diadic...
    double_couple_point_iter(&dim_two_ker.T1, exp_diadic_val_full_resp, &dim_two_ker.T1, &EcomXEaux);
    double_couple_point_iter(&dim_two_ker.T2, exp_diadic_val_full_resp, &dim_two_ker.T2, &EcomXEaux);
    double_couple_point_iter(&dim_two_ker.T1m2, exp_diadic_val_full_resp, &dim_two_ker.T1m2, &EcomXEaux);

    theta_couple_point_t pushed_points[3];
    theta_couple_point_t *const Tev1 = pushed_points + 0, *const Tev2 = pushed_points + 1,
                                *const Tev1m2 = pushed_points + 2;

    // Set points on the commitment curve
    copy_point(&Tev1->P1, &domain->B1.P);
    copy_point(&Tev2->P1, &domain->B1.Q);
    copy_point(&Tev1m2->P1, &domain->B1.PmQ);

    // Zero points on the aux curve
    ec_point_init(&Tev1->P2);
    ec_point_init(&Tev2->P2);
    ec_point_init(&Tev1m2->P2);

    theta_couple_curve_t codomain_product;

    // computation of the dim2 isogeny
    if (!theta_chain_compute_and_eval_randomized(pow_dim2_deg_resp,
                                                 &EcomXEaux,
                                                 &dim_two_ker,
                                                 true,
                                                 &codomain_product,
                                                 pushed_points,
                                                 sizeof(pushed_points) / sizeof(*pushed_points)))
        return 0;

    assert(test_couple_point_order_twof(Tev1, &codomain_product, reduced_order));

    // Set the auxiliary curve
    copy_curve(&codomain->E1, &codomain_product.E2);

    // Set the codomain curve from the dim 2 isogeny
    // it should always be the first curve
    copy_curve(&codomain->E2, &codomain_product.E1);

    // Set the evaluated basis points
    copy_point(&codomain->B1.P, &Tev1->P2);
    copy_point(&codomain->B1.Q, &Tev2->P2);
    copy_point(&codomain->B1.PmQ, &Tev1m2->P2);

    copy_point(&codomain->B2.P, &Tev1->P1);
    copy_point(&codomain->B2.Q, &Tev2->P1);
    copy_point(&codomain->B2.PmQ, &Tev1m2->P1);
    return 1;
}

static int
compute_small_chain_isogeny_signature(ec_curve_t *E_chall_2,
                                      ec_basis_t *B_chall_2,
                                      const quat_alg_elem_t *resp_quat,
                                      int pow_dim2_deg_resp,
                                      int length)
{
    int ret = 1;

    ibz_t two_pow;
    ibz_init(&two_pow);

    ibz_vec_2_t vec_resp_two;
    ibz_vec_2_init(&vec_resp_two);

    quat_left_ideal_t lideal_resp_two;
    quat_left_ideal_init(&lideal_resp_two);

    // computing the ideal
    ibz_pow(&two_pow, &ibz_const_two, length);

    // we compute the generator of the challenge ideal
    quat_lideal_create(&lideal_resp_two, resp_quat, &two_pow, &MAXORD_O0, &QUATALG_PINFTY);

    // computing the coefficients of the kernel in terms of the basis of O0
    id2iso_ideal_to_kernel_dlogs_even(&vec_resp_two, &lideal_resp_two);

    ec_point_t points[3];
    copy_point(&points[0], &B_chall_2->P);
    copy_point(&points[1], &B_chall_2->Q);
    copy_point(&points[2], &B_chall_2->PmQ);

    // getting down to the right order and applying the matrix
    ec_dbl_iter_basis(B_chall_2, pow_dim2_deg_resp + HD_extra_torsion, B_chall_2, E_chall_2);
    assert(test_basis_order_twof(B_chall_2, E_chall_2, length));

    ec_point_t ker;
    // applying the vector to find the kernel
    ec_biscalar_mul_ibz_vec(&ker, &vec_resp_two, length, B_chall_2, E_chall_2);
    assert(test_point_order_twof(&ker, E_chall_2, length));

    // computing the isogeny and pushing the points
    if (ec_eval_small_chain(E_chall_2, &ker, length, points, 3, true)) {
        ret = 0;
    }

    // copying the result
    copy_point(&B_chall_2->P, &points[0]);
    copy_point(&B_chall_2->Q, &points[1]);
    copy_point(&B_chall_2->PmQ, &points[2]);

    ibz_finalize(&two_pow);
    ibz_vec_2_finalize(&vec_resp_two);
    quat_left_ideal_finalize(&lideal_resp_two);

    return ret;
}

static int
compute_challenge_codomain_signature(const signature_t *sig,
                                     secret_key_t *sk,
                                     ec_curve_t *E_chall,
                                     const ec_curve_t *E_chall_2,
                                     ec_basis_t *B_chall_2)
{
    ec_isog_even_t phi_chall;
    ec_basis_t bas_sk;
    copy_basis(&bas_sk, &sk->canonical_basis);

    phi_chall.curve = sk->curve;
    phi_chall.length = TORSION_EVEN_POWER - sig->backtracking;
    assert(test_basis_order_twof(&bas_sk, &sk->curve, TORSION_EVEN_POWER));

    // Compute the kernel
    {
        ec_ladder3pt(&phi_chall.kernel, sig->chall_coeff, &bas_sk.P, &bas_sk.Q, &bas_sk.PmQ, &sk->curve);
    }
    assert(test_point_order_twof(&phi_chall.kernel, &sk->curve, TORSION_EVEN_POWER));

    // Double kernel to get correct order
    ec_dbl_iter(&phi_chall.kernel, sig->backtracking, &phi_chall.kernel, &sk->curve);

    assert(test_point_order_twof(&phi_chall.kernel, E_chall, phi_chall.length));

    // Compute the codomain from challenge isogeny
    if (ec_eval_even(E_chall, &phi_chall, NULL, 0))
        return 0;

#ifndef NDEBUG
    fp2_t j_chall, j_codomain;
    ec_j_inv(&j_codomain, E_chall_2);
    ec_j_inv(&j_chall, E_chall);
    // apparently its always the second one curve
    assert(fp2_is_equal(&j_chall, &j_codomain));
#endif

    // applying the isomorphism from E_chall_2 to E_chall
    ec_isom_t isom;
    if (ec_isomorphism(&isom, E_chall_2, E_chall))
        return 0; // error due to a corner case with 1/p probability
    ec_iso_eval(&B_chall_2->P, &isom);
    ec_iso_eval(&B_chall_2->Q, &isom);
    ec_iso_eval(&B_chall_2->PmQ, &isom);

    return 1;
}

static void
set_aux_curve_signature(signature_t *sig, ec_curve_t *E_aux)
{
    ec_normalize_curve(E_aux);
    fp2_copy(&sig->E_aux_A, &E_aux->A);
}

static void
compute_and_set_basis_change_matrix(signature_t *sig,
                                    const ec_basis_t *B_aux_2,
                                    ec_basis_t *B_chall_2,
                                    ec_curve_t *E_aux_2,
                                    ec_curve_t *E_chall,
                                    int f)
{
    // Matrices for change of bases matrices
    ibz_mat_2x2_t mat_Baux2_to_Baux2_can, mat_Bchall_can_to_Bchall;
    ibz_mat_2x2_init(&mat_Baux2_to_Baux2_can);
    ibz_mat_2x2_init(&mat_Bchall_can_to_Bchall);

    // Compute canonical bases
    ec_basis_t B_can_chall, B_aux_2_can;
    sig->hint_chall = ec_curve_to_basis_2f_to_hint(&B_can_chall, E_chall, TORSION_EVEN_POWER);
    sig->hint_aux = ec_curve_to_basis_2f_to_hint(&B_aux_2_can, E_aux_2, TORSION_EVEN_POWER);

#ifndef NDEBUG
    {
        // Ensure all points have the desired order
        assert(test_basis_order_twof(&B_aux_2_can, E_aux_2, TORSION_EVEN_POWER));
        assert(test_basis_order_twof(B_aux_2, E_aux_2, f));
        fp2_t w0;
        weil(&w0, f, &B_aux_2->P, &B_aux_2->Q, &B_aux_2->PmQ, E_aux_2);
    }
#endif

    // compute the matrix to go from B_aux_2 to B_aux_2_can
    change_of_basis_matrix_tate_invert(&mat_Baux2_to_Baux2_can, &B_aux_2_can, B_aux_2, E_aux_2, f);

    // apply the change of basis to B_chall_2
    matrix_application_even_basis(B_chall_2, E_chall, &mat_Baux2_to_Baux2_can, f);

#ifndef NDEBUG
    {
        // Ensure all points have the desired order
        assert(test_basis_order_twof(&B_can_chall, E_chall, TORSION_EVEN_POWER));
    }
#endif

    // compute the matrix to go from B_chall_can to B_chall_2
    change_of_basis_matrix_tate(&mat_Bchall_can_to_Bchall, B_chall_2, &B_can_chall, E_chall, f);

    // Assert all values in the matrix are of the expected size for packing
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall[0][0]) <= SQIsign_response_length + HD_extra_torsion);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall[0][1]) <= SQIsign_response_length + HD_extra_torsion);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall[1][0]) <= SQIsign_response_length + HD_extra_torsion);
    assert(ibz_bitsize(&mat_Bchall_can_to_Bchall[1][1]) <= SQIsign_response_length + HD_extra_torsion);

    // Set the basis change matrix to signature
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[0][0], &(mat_Bchall_can_to_Bchall[0][0]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[0][1], &(mat_Bchall_can_to_Bchall[0][1]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[1][0], &(mat_Bchall_can_to_Bchall[1][0]));
    ibz_to_digit_array(sig->mat_Bchall_can_to_B_chall[1][1], &(mat_Bchall_can_to_Bchall[1][1]));

    // Finalise the matrices
    ibz_mat_2x2_finalize(&mat_Bchall_can_to_Bchall);
    ibz_mat_2x2_finalize(&mat_Baux2_to_Baux2_can);
}

int
protocols_sign(signature_t *sig, const public_key_t *pk, secret_key_t *sk, const unsigned char *m, size_t l)
{
    int ret = 0;
    int reduced_order = 0; // work around false positive gcc warning

    uint_fast8_t pow_dim2_deg_resp = 0;
    assert(SQIsign_response_length <= (intmax_t)UINT_FAST8_MAX); // otherwise we might need more bits there

    ibz_t remain, lattice_content, random_aux_norm, degree_resp_inv, tmp;
    ibz_init(&remain);
    ibz_init(&lattice_content);
    ibz_init(&random_aux_norm);
    ibz_init(&degree_resp_inv);
    ibz_init(&tmp);

    quat_alg_elem_t resp_quat;
    quat_alg_elem_init(&resp_quat);
    quat_left_ideal_t lideal_commit, lideal_com_resp;
    quat_left_ideal_init(&lideal_commit);
    quat_left_ideal_init(&lideal_com_resp);

    // This structure holds two curves E1 x E2 together with a basis
    // Bi of E[2^n] for each of these curves
    theta_couple_curve_with_basis_t Ecom_Eaux;
    // This structure holds two curves E1 x E2 together with a basis
    // Bi of Ei[2^n]
    theta_couple_curve_with_basis_t Eaux2_Echall2;

    // This will hold the challenge curve
    ec_curve_t E_chall = sk->curve;

    ec_curve_init(&Ecom_Eaux.E1);
    ec_curve_init(&Ecom_Eaux.E2);
    size_t t = 1000;

    while (!ret) {

        // ibz_t rem, four;
        // ibz_init(&rem);
        // ibz_init(&four);
        // ibz_set(&four, 4);

        while(1) {
            // computing the commitment
            BENCH_CODE_1(t);
            ret = commit(&Ecom_Eaux.E1, &Ecom_Eaux.B1, &lideal_commit);

            // start again if the commitment generation has failed
            if (!ret) {
                continue;
            }

            // Hash the message to a kernel generator
            // i.e. a scalar such that ker = P + [s]Q
            hash_to_challenge(&sig->chall_coeff, pk, &Ecom_Eaux.E1, m, l);
            BENCH_CODE_2("test");
            // Compute the challenge ideal and response quaternion element
            quat_left_ideal_t lideal_chall_two;
            quat_lattice_t lattice_hom_chall_to_com;

            quat_lattice_init(&lattice_hom_chall_to_com);
            quat_left_ideal_init(&lideal_chall_two);
            // computing the challenge ideal
            // extracting the sampling function, avoid compute challenge isogeny repeatly
            compute_challenge_ideal_signature(&lideal_chall_two, sig, sk);
            compute_response_quat_element_extract(&resp_quat, &lattice_content, &lattice_hom_chall_to_com, sk, &lideal_chall_two, &lideal_commit);
            ibz_copy(&tmp, &lattice_content);

            int max_inner_retries = 80;
            int inner_success = 0;

            for (int i = 0; i < max_inner_retries; i++) {
                // compute_response_quat_element(&resp_quat, &lattice_content, sk, &lideal_chall_two, &lideal_commit);
                sample_response(&resp_quat, &lattice_hom_chall_to_com, &lattice_content);

                // computing the amount of backtracking we're making
                // and removing it
                compute_backtracking_signature(sig, &resp_quat, &lattice_content, &remain);

                // creating lideal_com * lideal_resp
                // we first compute the norm of lideal_resp
                // norm of the resp_quat
                pow_dim2_deg_resp = compute_random_aux_norm_and_helpers(sig,
                                                                        &random_aux_norm,
                                                                        &degree_resp_inv,
                                                                        &remain,
                                                                        &lattice_content,
                                                                        &resp_quat,
                                                                        &lideal_com_resp,
                                                                        &lideal_commit);
                ibz_copy(&lattice_content, &tmp);
                // ibz_mod(&rem, &random_aux_norm, &four);

                // && !ibz_cmp(&rem, &ibz_const_three) == 0
                if (ibz_probab_prime(&random_aux_norm, 40)) {  
                    inner_success = 1;  
                    break;             
                }
            }

            if (inner_success) {
                quat_left_ideal_finalize(&lideal_chall_two);
                quat_lattice_finalize(&lattice_hom_chall_to_com);
                break;
            }

            // Clean up
            quat_left_ideal_finalize(&lideal_chall_two);
            quat_lattice_finalize(&lattice_hom_chall_to_com);
        }
        // ibz_finalize(&rem);
        // ibz_finalize(&four);
        // ibz_print(&random_aux_norm, 10);
        // printf("\n");

        // notational conventions:
        // B0 = canonical basis of E0
        // B_com = image through commitment isogeny (odd degree) of canonical basis of E0
        // B_aux = image through aux_resp_com isogeny (odd degree) of canonical basis of E0

        if (pow_dim2_deg_resp > 0) {
            // Evaluate the random aux ideal on the curve E0 and its basis to find E_aux and B_aux
            ret =
                evaluate_random_aux_isogeny_signature(&Ecom_Eaux.E2, &Ecom_Eaux.B2, &random_aux_norm, &lideal_com_resp);

            // auxiliary isogeny computation failed we must start again
            if (!ret) {
                continue;
            }

#ifndef NDEBUG
            // testing that the order of the points in the bases is as expected
            assert(test_basis_order_twof(&Ecom_Eaux.B1, &Ecom_Eaux.E1, TORSION_EVEN_POWER));
            assert(test_basis_order_twof(&Ecom_Eaux.B2, &Ecom_Eaux.E2, TORSION_EVEN_POWER));
#endif

            // applying the matrix to compute Baux
            // first, we reduce to the relevant order
            reduced_order = pow_dim2_deg_resp + HD_extra_torsion + sig->two_resp_length;
            ec_dbl_iter_basis(&Ecom_Eaux.B1, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B1, &Ecom_Eaux.E1);
            ec_dbl_iter_basis(&Ecom_Eaux.B2, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B2, &Ecom_Eaux.E2);

            // Given all the above data, compute a dim two isogeny with domain
            // E_com x E_aux
            // and codomain
            // E_aux_2 x E_chall_2 (note: E_chall_2 is isomorphic to E_chall)
            // and evaluated points stored as bases in
            // B_aux_2 on E_aux_2
            // B_chall_2 on E_chall_2
            ret = compute_dim2_isogeny_challenge(
                &Eaux2_Echall2, &Ecom_Eaux, &degree_resp_inv, pow_dim2_deg_resp, sig->two_resp_length, reduced_order);
            if (!ret)
                continue;
        } 
        else {
            // No 2d isogeny needed, so simulate a "Kani matrix" identity here
            copy_curve(&Eaux2_Echall2.E1, &Ecom_Eaux.E1);
            copy_curve(&Eaux2_Echall2.E2, &Ecom_Eaux.E1);

            reduced_order = sig->two_resp_length;
            ec_dbl_iter_basis(&Eaux2_Echall2.B1, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B1, &Ecom_Eaux.E1);
            ec_dbl_iter_basis(&Eaux2_Echall2.B1, TORSION_EVEN_POWER - reduced_order, &Ecom_Eaux.B1, &Ecom_Eaux.E1);
            copy_basis(&Eaux2_Echall2.B2, &Eaux2_Echall2.B1);
        }

        // computation of the remaining small chain of two isogenies when needed
        if (sig->two_resp_length > 0) {
            if (!compute_small_chain_isogeny_signature(
                    &Eaux2_Echall2.E2, &Eaux2_Echall2.B2, &resp_quat, pow_dim2_deg_resp, sig->two_resp_length)) {
                assert(0); // this shouldn't fail
            }
        }

        // computation of the challenge codomain
        if (!compute_challenge_codomain_signature(sig, sk, &E_chall, &Eaux2_Echall2.E2, &Eaux2_Echall2.B2))
            assert(0); // this shouldn't fail
    }

    // Set to the signature the Montgomery A-coefficient of E_aux_2
    set_aux_curve_signature(sig, &Eaux2_Echall2.E1);

    // Set the basis change matrix from canonical bases to the supplied bases
    compute_and_set_basis_change_matrix(
        sig, &Eaux2_Echall2.B1, &Eaux2_Echall2.B2, &Eaux2_Echall2.E1, &E_chall, reduced_order);

    quat_alg_elem_finalize(&resp_quat);
    quat_left_ideal_finalize(&lideal_commit);
    quat_left_ideal_finalize(&lideal_com_resp);

    ibz_finalize(&lattice_content);
    ibz_finalize(&remain);
    ibz_finalize(&degree_resp_inv);
    ibz_finalize(&random_aux_norm);
    // test_norm_with_factors(10, &QUAT_represent_integer_params);

    return ret;
}

// The following code is for testing the algorithm's performance while N prime factors are known
#define MAX_FACTORS 15
#define NUM_TEST_CASES 48

typedef struct {
    const char *norm_str;
    int num_factors;
    const char *primes_str[MAX_FACTORS];
    const char *powers_str[MAX_FACTORS]; 
} precomputed_factorization_t;

// Pre-calculated prime factorization
precomputed_factorization_t test_data[NUM_TEST_CASES] = {
    // [1/50]
    {
        "5268829680383359026813028132863024243018511237132440685922611281167700060927", 10,
        {"3", "97", "149", "157", "719", "42787", "305643223943", "3439523520749", "3430687502934076937", "6975900964532934227"},
        {"3", "97", "149", "157", "719", "42787", "305643223943", "3439523520749", "3430687502934076937", "6975900964532934227"}
    },
    // [2/50]
    {
        "1287070750254053188631400033452127527335766132372083099630024467637299999223", 3,
        {"29", "1367", "32466532559444370724501173812580468868041423009663322645360453740567061"},
        {"29", "1367", "32466532559444370724501173812580468868041423009663322645360453740567061"}
    },
    // [3/50]
    {
        "110749011058082038738436139221772788142234847819459667330904448136801981929", 4,
        {"1418917", "9928403", "237016992634622592281", "33168358923369468604200080514134756150959"},
        {"1418917", "9928403", "237016992634622592281", "33168358923369468604200080514134756150959"}
    },
    // [4/50]
    {
        "754414717147644826864912687970496131773847618934424166082124810249571416623", 4,
        {"3", "107", "24877", "94472870967232907633270668382585139042825607776481368217251908705419"},
        {"3", "107", "24877", "94472870967232907633270668382585139042825607776481368217251908705419"}
    },
    // [5/50]
    {
        "540181500459265029167742131558877564843999835264540284860656499541605852345", 5,
        {"5", "1667", "2689401101552687", "202737673410934933", "118862282577171438110359911622355288917"},
        {"5", "1667", "2689401101552687", "202737673410934933", "118862282577171438110359911622355288917"}
    },
    // [6/50]
    {
        "2357666231003374175705709914332243779330230836677432278727382508789385080975", 7,
        {"5", "3847", "7177", "34511", "6511499", "899024544096193592153", "16907021756007580360250093516976493"},
        {"25", "3847", "7177", "34511", "6511499", "899024544096193592153", "16907021756007580360250093516976493"}
    },
    // [7/50]
    {
        "5749541617669097280112266411665708840765622205281353441299401037064031999689", 9,
        {"7", "11", "13", "19", "47", "987726473", "14565882967", "399613778849", "1118751732933623876175526157854946539547"},
        {"7", "11", "13", "19", "47", "987726473", "14565882967", "399613778849", "1118751732933623876175526157854946539547"}
    },
    // [8/50]
    {
        "5438738221614023236824192589145870959832851332657714027932600714318421621711", 7,
        {"3", "17", "19", "379", "103007", "828511633", "173528103044572422974127676731149455003545698717065343131"},
        {"3", "17", "19", "379", "103007", "828511633", "173528103044572422974127676731149455003545698717065343131"}
    },
    // [9/50]
    {
        "69141091341214728830063107288504813854050667447411750637119960469695650995", 4,
        {"5", "508311518064768853", "8966506519860684116799287", "3033982047243136215265276930909"},
        {"5", "508311518064768853", "8966506519860684116799287", "3033982047243136215265276930909"}
    },
    // [10/50]
    {
        "226288195175174751999024581169231423406861766627136575923132546763875319697", 9,
        {"3", "31", "331", "977", "62417", "2666683", "4116779", "135040431407475813071", "27104380430390496780937869811"},
        {"9", "31", "331", "977", "62417", "2666683", "4116779", "135040431407475813071", "27104380430390496780937869811"}
    },
    // [11/50]
    {
        "2440801152817361745955445629601133184420465254671285839957795082351414190039", 5,
        {"3", "7", "167206500420046429", "9214259412217084434109", "10777089083512155015125632986962917"},
        {"3", "49", "167206500420046429", "9214259412217084434109", "10777089083512155015125632986962917"}
    },
    // [12/50]
    {
        "4821102370557657333618902397150302303461187713560065868159485402577991359479", 3,
        {"86828299513", "341215045653113", "162725975911227864700957504877478523658701672010791"},
        {"86828299513", "341215045653113", "162725975911227864700957504877478523658701672010791"}
    },
    // [13/50]
    {
        "854634061053116234285223931380260001180505328829014589201855994274044964347", 4,
        {"5737", "310768408859", "200229339795923", "2394036502739214050716531973983208789106657283"},
        {"5737", "310768408859", "200229339795923", "2394036502739214050716531973983208789106657283"}
    },
    // [14/50]
    {
        "76377977708900851199545338967677983707143083665060682420185572499305922807", 2,
        {"20107", "3798576501163816143608959017639527712097432917146301408473943029756101"},
        {"20107", "3798576501163816143608959017639527712097432917146301408473943029756101"}
    },
    // [15/50]
    {
        "663771694514204486671760297572327466187172211355013551437636505489416168983", 5,
        {"467", "4229", "55442076897452033", "15354697721055735577", "394805687967064202846717851206641"},
        {"467", "4229", "55442076897452033", "15354697721055735577", "394805687967064202846717851206641"}
    },
    // [16/50]
    {
        "3674875062328662712089816382335342317265324474553593417589339214369401580655", 7,
        {"3", "5", "67577", "1393831", "40111639", "42208672651", "1536279336891687245978897742628482309181266139"},
        {"3", "5", "67577", "1393831", "40111639", "42208672651", "1536279336891687245978897742628482309181266139"}
    },
    // [17/50]
    {
        "386183030551089234867084348124084800048039203631257917841616101206584503685", 7,
        {"3", "5", "293", "4889", "227564467231", "1448016860799497", "54542645665232577754849536730665288243761"},
        {"3", "5", "293", "4889", "227564467231", "1448016860799497", "54542645665232577754849536730665288243761"}
    },
    // [18/50]
    {
        "2855150306128519575743915826071976970662002160243982840717881653706501192573", 6,
        {"3", "17", "12425641", "31750302257", "1092669271371206834466294751", "14429819375424116250983544881"},
        {"27", "17", "12425641", "31750302257", "1092669271371206834466294751", "14429819375424116250983544881"}
    },
    // [19/50]
    {
        "9552117125533939136916040099757594665404845202471099215477486042479465782281", 8,
        {"37", "193", "383", "12377", "143593", "11159319893", "365786297139089543", "481424305509780225261840576229193"},
        {"37", "193", "383", "12377", "143593", "11159319893", "365786297139089543", "481424305509780225261840576229193"}
    },
    // [20/50]
    {
        "7938620409951082914362331985028643981197489481238363922486165479004560426689", 8,
        {"3", "13", "631", "9343", "629513", "72471170617", "10243361727806630929943", "73884311778808686938184195449"},
        {"3", "13", "631", "9343", "629513", "72471170617", "10243361727806630929943", "73884311778808686938184195449"}
    },
    // [21/50]
    {
        "17637364598519316577878135405249390331101479324102211782651767734170093331", 6,
        {"3", "53", "15269", "2206394118889", "299250684204567637", "3667638097440428685339450773701638559"},
        {"9", "53", "15269", "2206394118889", "299250684204567637", "3667638097440428685339450773701638559"}
    },
    // [22/50]
    {
        "4216983195378814673630593805081026068088881095449324490190406411766136736251", 9,
        {"3", "13", "31", "433", "113263967", "125734187", "230850621713", "1052475046553154727", "2328089490806904526685377"},
        {"3", "13", "31", "433", "113263967", "125734187", "230850621713", "1052475046553154727", "2328089490806904526685377"}
    },
    // [23/50]
    {
        "4364736016881820936460216002015088154476576803241369004486999752752260970741", 7,
        {"7", "11", "4801", "42073", "53214841144074293", "30427443582154871071", "173314075540504823206460993107"},
        {"7", "11", "4801", "42073", "53214841144074293", "30427443582154871071", "173314075540504823206460993107"}
    },
    // [24/50]
    {
        "1503178309595419483759583234848432923235278980543500952681203479603709262141", 4,
        {"15901", "1563157", "98860864468186834999016359194959", "611728985756004108487615780265107"},
        {"15901", "1563157", "98860864468186834999016359194959", "611728985756004108487615780265107"}
    },
    // [25/50]
    {
        "873241512095386966276854523602085603154205539027729750861962628137901449035", 10,
        {"3", "5", "13", "311", "983", "1123", "533921903", "2465770162927", "64296816208507879", "17121578063806715978892157"},
        {"27", "5", "13", "311", "983", "1123", "533921903", "2465770162927", "64296816208507879", "17121578063806715978892157"}
    },
    // [26/50]
    {
        "3268661220412973800367498793359787756533620168713254963506513755349580629087", 1,
        {"3268661220412973800367498793359787756533620168713254963506513755349580629087"},
        {"3268661220412973800367498793359787756533620168713254963506513755349580629087"}
    },
    // [27/50]
    {
        "1530569031380731519091879173529996303025205082044362024840678290459211339409", 4,
        {"4403089", "82093703", "12808014951895313", "330600713191814061281954189462456241485614279"},
        {"4403089", "82093703", "12808014951895313", "330600713191814061281954189462456241485614279"}
    },
    // [28/50]
    {
        "336802510556530177002236709740632984661890953530132378142525829740377227153", 5,
        {"7", "13", "859", "867998195122321988403101", "4963887632701158731600520716792890091507367437"},
        {"7", "13", "859", "867998195122321988403101", "4963887632701158731600520716792890091507367437"}
    },
    // [29/50]
    {
        "7703074906939326302091721546223748235114950002995578069790101323283283222281", 6,
        {"3", "31", "79", "6007", "8287", "21061975849470068485308087563493812065899580502154536516616171547"},
        {"3", "31", "79", "6007", "8287", "21061975849470068485308087563493812065899580502154536516616171547"}
    },
    // [30/50]
    {
        "3570487954389202846301320971873147966928016689908483737022861250671339692545", 8,
        {"5", "19", "23", "3889", "1204571903", "129563663347747", "27466947113323573", "98019356861556681168449844041"},
        {"5", "19", "23", "3889", "1204571903", "129563663347747", "27466947113323573", "98019356861556681168449844041"}
    },
    // [31/50]
    {
        "1674056536135947582868676159265069793067660664162189163505600722076250993", 5,
        {"3", "197", "1987", "5488709", "259725485573912745434241193952246984660730066468842435008081"},
        {"3", "197", "1987", "5488709", "259725485573912745434241193952246984660730066468842435008081"}
    },
    // [32/50]
    {
        "234588608692192159009504981148537891138683454068078925261160074446054397097", 6,
        {"3", "17", "3779", "13800013", "2386899124918799241187", "12317569915133851182116803110754576015501"},
        {"9", "17", "3779", "13800013", "2386899124918799241187", "12317569915133851182116803110754576015501"}
    },
    // [33/50]
    {
        "8595621393195843636165405598330388223359491670995455745922302607463997503743", 5,
        {"17", "277", "14199706582343", "128847547456307431", "997684122792845739530546186370000767045219"},
        {"17", "277", "14199706582343", "128847547456307431", "997684122792845739530546186370000767045219"}
    },
    // [34/50]
    {
        "3903222731228997251263521570325999184744052249305180813636345146074588915179", 4,
        {"7", "119083", "9179869799", "510080834286230471879641793565594127817890088226767948169841"},
        {"7", "119083", "9179869799", "510080834286230471879641793565594127817890088226767948169841"}
    },
    // [35/50]
    {
        "147620815731244314432624525701669111164121113358175694867981608631795219001", 4,
        {"11", "103", "211", "617497545547593372594774288374483341897830753224780475723895410966127"},
        {"11", "103", "211", "617497545547593372594774288374483341897830753224780475723895410966127"}
    },
    // [36/50]
    {
        "1137276413316713813755890582484396868677832796658244618128047812508014785089", 7,
        {"3", "1051", "8081", "85607", "7563811", "917064539", "8351886780038135510722486874150580059023954799"},
        {"27", "1051", "8081", "85607", "7563811", "917064539", "8351886780038135510722486874150580059023954799"}
    },
    // [37/50]
    {
        "3436600408128792370270260540414552114872571079291185331929188544274956500069", 5,
        {"383", "2339", "12795946134596593", "5431222111014056699911", "55198855691183627224874037174719"},
        {"383", "2339", "12795946134596593", "5431222111014056699911", "55198855691183627224874037174719"}
    },
    // [38/50]
    {
        "1933596970988765424379953759672348987959589255487313343970206703045177108301", 1,
        {"1933596970988765424379953759672348987959589255487313343970206703045177108301"},
        {"1933596970988765424379953759672348987959589255487313343970206703045177108301"}
    },
    // [39/50]
    {
        "1485968428955242423904001148944154890706397476643808261147631515166857865601", 5,
        {"37", "197", "58057", "257473", "13638146405621211637165423473877318693037053982251034433240769"},
        {"37", "197", "58057", "257473", "13638146405621211637165423473877318693037053982251034433240769"}
    },
    // [40/50]
    {
        "1640490191715593421131952488480456595700969152373434084556784894628553293029", 4,
        {"11", "17", "503", "17440705411547755404811265970811033219942049865230372678971995775385689"},
        {"11", "17", "503", "17440705411547755404811265970811033219942049865230372678971995775385689"}
    },
    // [42/50]
    {
        "5379940007425766780148747868594189651325929806731836710266425317921994621337", 5,
        {"593", "4201", "47609121480251", "1017342274324879238587763", "44587466790523514974243859162593"},
        {"593", "4201", "47609121480251", "1017342274324879238587763", "44587466790523514974243859162593"}
    },
    // [43/50]
    {
        "2249920170523062904073950270751211736388614001434543187378790989942060561755", 3,
        {"5", "7", "64283433443516082973541436307177478182531828612415519639394028284058873193"},
        {"5", "7", "64283433443516082973541436307177478182531828612415519639394028284058873193"}
    },
    // [44/50]
    {
        "1559310447943198343800068431052641134660124816108615177330896696944203812735", 9,
        {"5", "7", "4129", "321359", "70613467", "132652133", "27970973249", "5880625997353987843", "21791959548561848143"},
        {"5", "7", "4129", "321359", "70613467", "132652133", "27970973249", "5880625997353987843", "21791959548561848143"}
    },
    // [45/50]
    {
        "1076154678338919948805930694469866309544889211971993717787845585543774851527", 5,
        {"13", "7741", "26783", "25695639018893", "15538734076807594208833705895230793416573481287293701"},
        {"13", "7741", "26783", "25695639018893", "15538734076807594208833705895230793416573481287293701"}
    },
    // [46/50]
    {
        "1943056529387796199297345502521079121612924230398739848986581922736953841451", 4,
        {"383", "51691", "810503", "121092459741943971576702080432517651049679595564485229954884489"},
        {"383", "51691", "810503", "121092459741943971576702080432517651049679595564485229954884489"}
    },
    // [47/50]
    {
        "5483342361865425716258935960061699994247109633831872960044209498945540344383", 12,
        {"3", "11", "167", "751", "1109", "5351", "1474519", "3784457", "6221981", "5011327901", "6683306057", "17453761352195898839177"},
        {"3", "121", "167", "751", "1109", "5351", "1474519", "3784457", "6221981", "5011327901", "6683306057", "17453761352195898839177"}
    },
    // [48/50]
    {
        "8948312742109812786193194267385898522714322147777588701239974017608569982777", 4,
        {"7", "11", "95678467", "1214608233570819359890280246378141049828158921714816004625262779103"},
        {"7", "11", "95678467", "1214608233570819359890280246378141049828158921714816004625262779103"}
    },
    // [49/50]
    {
        "2463588986095380685385201804535662330436494054231450338694669943170890993047", 9,
        {"3", "19", "89", "241", "96017", "167537", "396486263", "30876884724050983", "10232125553766634011552764384668919"},
        {"3", "19", "89", "241", "96017", "167537", "396486263", "30876884724050983", "10232125553766634011552764384668919"}
    }
};

void test_norm_with_factors(size_t runs, const quat_represent_integer_params_t *params) {

    // Initialization
    ibz_t norms[NUM_TEST_CASES];
    ibz_t primes[NUM_TEST_CASES][MAX_FACTORS];
    ibz_t powers[NUM_TEST_CASES][MAX_FACTORS];
    int num_factors[NUM_TEST_CASES];

    // String to ibz_t
    for (int i = 0; i < NUM_TEST_CASES; i++) {
        ibz_init(&norms[i]);
        ibz_set_from_str(&norms[i], test_data[i].norm_str, 10);
        num_factors[i] = test_data[i].num_factors;

        for (int j = 0; j < num_factors[i]; j++) {
            ibz_init(&primes[i][j]);
            ibz_init(&powers[i][j]);
            ibz_set_from_str(&primes[i][j], test_data[i].primes_str[j], 10);
            ibz_set_from_str(&powers[i][j], test_data[i].powers_str[j], 10);
        }
    }

    quat_left_ideal_t lideal;
    quat_left_ideal_init(&lideal);

    BENCH_CODE_1(runs);
    int idx = i % NUM_TEST_CASES;
    quat_generate_random_O0_ideal_norm_non_prime(&lideal, 
                                                 params, 
                                                 &norms[idx], 
                                                 primes[idx], 
                                                 powers[idx], 
                                                 num_factors[idx]);
    BENCH_CODE_2("composite");
   
    quat_left_ideal_finalize(&lideal);
    for (int i = 0; i < NUM_TEST_CASES; i++) {
        ibz_finalize(&norms[i]);
        for (int j = 0; j < num_factors[i]; j++) {
            ibz_finalize(&primes[i][j]);
            ibz_finalize(&powers[i][j]);
        }
    }
}










